### ISSUE TITLE
AWS S3 Issue 

### ISSUE THREAD

**Issue by rakeshponnala** [nf-core/smrnaseq#116]
Hello, 

I'm trying to run smRNASeq pipeline as below. However keep running in to the S3 Issue. 

nextflow run nf-core/smrnaseq -profile singularity --genome CanFam3.1 --mirtrace_species cfa --mirtrace_protocol qiaseq --input '*.fastq.gz' --protocol qiaseq  
N E X T F L O W  ~  version 21.04.3
Launching `nf-core/smrnaseq` [tender_marconi] - revision: 03333bfa17 [master]

------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/smrnaseq v1.1.0
------------------------------------------------------

Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: KR7X00MMWCJEK9JE; S3 Extended Request ID: Ep7w7RBLvRc/uP/NXcIxainkPrD73+6nof37vxNW85gFlYZQCukp4d+Os2ZR/msdmpDUDMbly4E=)

cat .nextflow.log:

Oct-19 10:31:59.899 [main] DEBUG nextflow.plugin.PluginUpdater - Starting plugin nf-amazon version: 1.0.5
Oct-19 10:31:59.900 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-amazon@1.0.5'
Oct-19 10:31:59.925 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-amazon@1.0.5
Oct-19 10:31:59.940 [main] DEBUG nextflow.file.FileHelper - > Added 'S3FileSystemProvider' to list of installed providers [s3]
Oct-19 10:31:59.940 [main] DEBUG nextflow.file.FileHelper - Started plugin 'nf-amazon' required to handle file: s3://ngi-igenomes/igenomes/Canis_familiaris/Ensembl/CanFam3.1/Sequence/WholeGenomeFasta/genome.fa
Oct-19 10:31:59.946 [main] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
Oct-19 10:31:59.953 [main] DEBUG nextflow.Global - Using AWS credential defined in `default` section in file: /sc/kzd/home/ponnar02/.aws/credentials
Oct-19 10:31:59.955 [main] DEBUG nextflow.file.FileHelper - AWS S3 config details: {secret_key=nolvM8.., region=us-east-1, access_key=AKIAI4..}
Oct-19 10:32:01.477 [main] DEBUG nextflow.Session - Session aborted -- Cause: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: KR7X00MMWCJEK9JE; S3 Extended Request ID: Ep7w7RBLvRc/uP/NXcIxainkPrD73+6nof37vxNW85gFlYZQCukp4d+Os2ZR/msdmpDUDMbly4E=)
Oct-19 10:32:01.496 [main] ERROR nextflow.cli.Launcher - @unknown
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: KR7X00MMWCJEK9JE; S3 Extended Request ID: Ep7w7RBLvRc/uP/NXcIxainkPrD73+6nof37vxNW85gFlYZQCukp4d+Os2ZR/msdmpDUDMbly4E=)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4914)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4860)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4854)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:880)
	at com.upplication.s3fs.AmazonS3Client.listObjects(AmazonS3Client.java:105)
	at com.upplication.s3fs.util.S3ObjectSummaryLookup.lookup(S3ObjectSummaryLookup.java:113)
	at com.upplication.s3fs.S3FileSystemProvider.getAccessControl(S3FileSystemProvider.java:921)
	at com.upplication.s3fs.S3FileSystemProvider.checkAccess(S3FileSystemProvider.java:607)
	at java.nio.file.Files.exists(Files.java:2385)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:44)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:89)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:94)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.extension.FilesEx.exists(FilesEx.groovy:454)
	at nextflow.file.FileHelper.checkIfExists(FileHelper.groovy:986)
	at nextflow.file.FileHelper$checkIfExists$2.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at nextflow.Nextflow.file(Nextflow.groovy:159)
	at nextflow.Nextflow$file.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
	at Script_4145bff8.runScript(Script_4145bff8:104)
	at nextflow.script.BaseScript.runDsl1(BaseScript.groovy:164)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:302)
	at nextflow.cli.Launcher.run(Launcher.groovy:475)
	at nextflow.cli.Launcher.main(Launcher.groovy:657)

**Comment by rakeshponnala** [comment]
Thanks! I downloaded the entire dog genome from igenome to avoid aws s3, In that case, should I explicitly specify fasta file location and run them ? as opposed to using --genome and pulling from AWS? Then I dont need to make any configuration changes to my Nextflow config file correct?

**Comment by wushyer** [comment]
Hi, I am using the singularity profile of smrnaseq (latest version) in rat, with specified Rat genome of Rn6. The output is fine except for the empty mirtop results. 

Below is the log

(tools3) [shuangyang.wu@clip-login-0 log]$ cat run.log
01/11/2022 05:06:55 INFO-mirtop.libs.logger(44): Run export of GFF into other format.
01/11/2022 05:06:55 INFO-mirtop.libs.logger(32): INFO Writing TSV file to directory mirtop
01/11/2022 05:06:55 INFO-mirtop.libs.logger(34): INFO Reading GFF file mirtop/mirtop.gff
01/11/2022 05:06:55 INFO-mirtop.libs.logger(94): Missing Parents in hairpin file: 0
01/11/2022 05:06:55 INFO-mirtop.libs.logger(95): Missing MiRNAs in GFF file: 0
01/11/2022 05:06:55 INFO-mirtop.libs.logger(96): Non valid UID: 0
01/11/2022 05:06:55 INFO-mirtop.libs.logger(97): Output file is at mirtop/mirtop_rawData.tsv
01/11/2022 05:06:55 INFO-mirtop.libs.logger(57): It took 0.001 minutes
(tools3) [shuangyang.wu@clip-login-0 log]$ cat trace.log
INFO - Run export of GFF into other format.
INFO - INFO Writing TSV file to directory mirtop
INFO - INFO Reading GFF file mirtop/mirtop.gff
INFO - Missing Parents in hairpin file: 0
INFO - Missing MiRNAs in GFF file: 0
INFO - Non valid UID: 0
INFO - Output file is at mirtop/mirtop_rawData.tsv
INFO - It took 0.001 minutes

I also check the running pipeline, it seems the mapping for mirtop is good, only the gff3 parent id can not match the modified hairpin fasta.

##gff3
chr1    .       miRNA_primary_transcript        38238376        38238456        .       +       .       ID=MI0000862;Alias=MI0000862;Name=rno-mir-29b-2
chr1    .       miRNA   38238386        38238407        .       +       .       ID=MIMAT0004717;Alias=MIMAT0004717;Name=rno-miR-29b-5p;Derives_from=MI0000862
chr1    .       miRNA   38238427        38238449        .       +       .       ID=MIMAT0000801;Alias=MIMAT0000801;Name=rno-miR-29b-3p;Derives_from=MI0000862
chr1    .       miRNA_primary_transcript        38238896        38239002        .       -       .       ID=MI0015414;Alias=MI0015414;Name=rno-mir-3556b-1
chr1    .       miRNA   38238957        38238976        .       -       .       ID=MIMAT0017818;Alias=MIMAT0017818;Name=rno-miR-3556b;Derives_from=MI0015414
chr1    .       miRNA_primary_transcript        38238904        38238991        .       +       .       ID=MI0000865;Alias=MI0000865;Name=rno-mir-29c-1
chr1    .       miRNA   38238919        38238940        .       +       .       ID=MIMAT0003154;Alias=MIMAT0003154;Name=rno-miR-29c-5p;Derives_from=MI0000865
chr1    .       miRNA   38238957        38238978        .       +       .       ID=MIMAT0000803;Alias=MIMAT0000803;Name=rno-miR-29c-3p;Derives_from=MI0000865
###hairpin
>rno-mir-322-1_MI0000589_Rattus_norvegicus_miR-322-1_stem-loop
CCTCGCTGACTCCGAAGGGATGCAGCAGCAATTCATGTTTTGGAGTATTGCCAAGGTTCAAAACATGAAGCGCTGCAACACCCCTTCGTGGGAAA
>rno-mir-323_MI0000591_Rattus_norvegicus_miR-323_stem-loop
TTGGTACTTGGAGAGAGGTGGTCCGTGGCGCGTTCGCTTCATTTATGGCGCACATTACACGGTCGACCTCTTTGCGGTATCTAATC
>rno-mir-301a_MI0000593_Rattus_norvegicus_miR-301a_stem-loop
CCTGCTGGCTACTGCTGACGACTGCTCTGACTTTATTGCACTACTGTACTGTACAGCTAGCAGTGCAATAGTATTGTCAAAGCATCCGGGAGCAGGCTAC
>rno-mir-324_MI0000594_Rattus_norvegicus_miR-324_stem-loop
CTGACTATGCCTCCTCGCATCCCCTAGGGCATTGGTGTAAAGCTGGAGACCCACTGCCCCAGGTGCTGCTGGGGGTTGTAGTC
>rno-mir-325_MI0000596_Rattus_norvegicus_miR-325_stem-loop
ATATAGTGCTTGGTTCCTAGTAGGTGCTCAGTAAGTGTTTGTGACATAATTCGTTTATTGAGCACCTCCTATCAATCAAGCACTGTGCTAGGCTCTGG

**Comment by apeltzer** [comment]
Please don't bump a different thread - open a separate issue if its not evidently clear that it is the same issue 👍🏻
