### ISSUE TITLE
mirTop error, Database not found in --mirna hsa.gff3. Use --database argument to add a custom source.

### ISSUE THREAD

**Issue by mdozmorov** [nf-core/smrnaseq#284]
### Description of the bug

This error still occurs in 2.2.3. It appears to have a fix, when running the pipeline with `-r fix-mirtop-gff` (using fix-mirtop-gff branch), the pipeline completes. Would be good to have it in the main branch, for reproducibility. Shortened message:
```
ERROR ~ Error executing process > 'NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:MIRTOP_QUANT'

Caused by:
  Process `NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:MIRTOP_QUANT` terminated with an error exit status (1)
...
Command error:
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  /usr/local/lib/python3.9/site-packages/mirtop/mirna/mintplates.py:512: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if prefix is '':
  09/10/2023 09:09:02 INFO Run annotation
  09/10/2023 09:09:02 ERROR Database not found in --mirna hsa.gff3. Use --database argument to add a custom source.
  Traceback (most recent call last):
    File "/usr/local/bin/mirtop", line 10, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.9/site-packages/mirtop/command_line.py", line 31, in main
      reader(kwargs["args"])
    File "/usr/local/lib/python3.9/site-packages/mirtop/gff/__init__.py", line 24, in reader
      database = mapper.guess_database(args)
    File "/usr/local/lib/python3.9/site-packages/mirtop/mirna/mapper.py", line 23, in guess_database
      return _guess_database_file(args.gtf, args.database)
    File "/usr/local/lib/python3.9/site-packages/mirtop/mirna/mapper.py", line 40, in _guess_database_file
      raise ValueError("Database not found in %s header" % gff)
  ValueError: Database not found in hsa.gff3 header
```

### Command used and terminal output

```console
nextflow run nf-core/smrnaseq --input ${INPUT} \
  --outdir ${DIROUT} \
  -profile 'singularity' \
  --genome GRCh38 \
  --mirtrace_species 'hsa' \
  --protocol 'illumina' \
  --skip_mirdeep \
  -resume
#  -r fix-mirtop-gff # Using this fixes the problem
```

### System information

nextflow version 23.04.3.5875, HPC, local, singularity, CentOS 7, 2.2.3

**Comment by yangfeizZZ** [comment]
Hello, I wonder if you have solved this error. I met the same error.

**Comment by shepp-hub** [comment]
I can confirm that the issue persists.

**Comment by christopher-mohr** [comment]
> I can confirm that the issue persists.

Hi @shepp-hub, could you please check if the issue still exists with the latest release `2.3.0`.

**Comment by christopher-mohr** [comment]
Please reopen if the problem persists.

**Comment by drejom** [comment]
I still get this error in 2.4.0 using a custom mouse genome from Gencode (with transgenes added); the `fix-mirtop-gff` branch is no longer available, but version 2.3.1 seems to be running fine like this, 2.4.0 fails with the error above:

```sh
nextflow run nf-core/smrnaseq \
-r 2.3.1 -resume -profile gemini \
--input sample_sheet.csv \
--outdir nfcore-smrnaseq-2.4.0_GENCODE_mmu_M33_primary_2024_A_HLT_AML.miRNA.2018 \
--genome GENCODE_mmu_M33_primary_2024_A_HLT \
--mirtrace_species mmu \
--three_prime_adapter TCTGGAATTCTCGGGTGCCAAGGAACTCC \
--mature /ref_genomes/nf-core/smrnaseq/mature.fa \
--hairpin /ref_genomes/nf-core/smrnaseq/hairpin.fa 
```
I had to set `--mature` and `--hairpin` to manually downloaded paths to override the defaults when they are not provided on the cli (per `pipeline_info/params_YYYMMDD.json`, post failed run):

```json
"mature": "https://github.com/nf-core/test-datasets/raw/smrnaseq/miRBase/mature.fa",
"hairpin": "https://github.com/nf-core/test-datasets/raw/smrnaseq/miRBase/hairpin.fa",
```

**Comment by tylerstahl** [comment]
Issue looks to be [here](https://github.com/nf-core/smrnaseq/blob/master/subworkflows/local/prepare_genome/main.nf#L63), using the https link to download the gff3 from miRBase.

[mmu.gff3.txt](https://github.com/user-attachments/files/28526233/mmu.gff3.txt)

The gff3 file gets wrapped in html tags (example from work dir attached as text file). This causes the [if statement](https://github.com/miRTop/mirtop/blob/603f45c7154b949bfc76dbc1eb6f9826ce2621e0/mirtop/mirna/mapper.py#L29) that checks the gff header in miRTop to break 

I was able to download the gff3, correctly formatted, from miRBase website and pass the file to the `--mirna_gtf ` param
